id: P003059
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:37:41.164373
source_metadata:
  id: bdr:W00EGS1017717
  title: རྫོང་སར་དགོན་དུ་བསྟན་པ་སླར་གསོ་སྐབས་དབང་ལུང་གསན་ཡིག་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    c4ccb6ae5f604a5da38f85978f24390d:
      image_group_id: I2KG207974
      title: ''
      volume_number: 1
      total_pages: 492
      base_file: v001.txt
    86f2b1900ddf494ba8b7d54587e1c054:
      image_group_id: I2KG207975
      title: ''
      volume_number: 2
      total_pages: 499
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
