id: IDF36116E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:26:34+00:00'
last_modified: '2022-06-07T17:16:48.313436+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017717
  title: རྫོང་སར་དགོན་དུ་བསྟན་པ་སླར་གསོ་སྐབས་དབང་ལུང་གསན་ཡིག་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2E1E:
      image_group_id: I2KG207974
      title: ''
      total_pages: 492
      order: 1
      base_file: 2E1E.txt
    56D7:
      image_group_id: I2KG207975
      title: ''
      total_pages: 499
      order: 2
      base_file: 56D7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
