id: IDF36116E
legacy_id: P003059
ocr_import_info:
  bdrc_scan_id: W00EGS1017717
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T00:23:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:16:49.209466+00:00'
last_modified: 2022-08-29 19:18:35.636942
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1017717
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1017717
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫོང་སར་དགོན་དུ་བསྟན་པ་སླར་གསོ་སྐབས་དབང་ལུང་གསན་ཡིག་སྐོར་ཕྱོགས་བསྒྲིགས།
statistics:
  ocr_word_mean_confidence_index: 0.9506245042927989
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2KG207975:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2KG207975
      total_pages: 499
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2KG207975.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9554586150256407
    legacy_id: v002
  I2KG207974:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2KG207974
      total_pages: 492
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2KG207974.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9441331844593265
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
